name: 'Validate master branch with Repolinter'

on:
  push:
    branches:
      - master

jobs:
  repolinter-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: 'Run Repolinter'
        uses: newrelic/repolinter-action@v1
        with:
          config_file: 'repolinter.yml'
          output_type: issue
          output_name: 'Open Source Repository Guidelines issues'
          label_name: 'repolinter'
          label_color: '00ffff'
